# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
sudo: required

language: c

addons:
  apt:
    packages: [ libjansson-dev, libsqlite3-dev, libmysqlclient-dev, libpq-dev, check, libsubunit-dev, cppcheck ]

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)

script:
  - cmake -DWITH_JOURNALD=off -DBUILD_HOEL_TESTING=on .
  - make
  - sqlite3 /tmp/test.db < test/test.sql
  - make test
